[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
mcap = { path = "..", features = ["tokio"] }
thiserror = "1.0.63"
reqwest-middleware = { version = "0.3.3", features = ["rustls-tls"] }
async_http_range_reader = "0.8.0"
percent-encoding = "2.3.1"
url = "2.5.2"
async-trait = "0.1.81"
tabled = "0.16.0"
chrono = "0.4.38"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
google-cloud-auth = "0.16.0"
google-cloud-token = "0.1.2"
regex = "1.10.6"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.2"
tempfile = "3.12.0"
walkdir = "2.5.0"
